name: App Deploy

on:
  push:
    branches: [ "master" ]
    
env:
  workdir_deploy: ./deploy-api
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build-and-test:
    uses: ./.github/workflows/neoway-app.yml
    
  deploy:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        echo "AWS_SG_NAME=allow_ssh" >> $GITHUB_ENV
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr 0.0.0.0/0    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install boto3 netmiko argparse
    - name: Run deploy API
      run: |
        echo ${{ env.SSH_KEY }} > aws_key
        chmod 400 aws_key
        python deploy-api.py -a ${{ secrets.AWS_ACCESS_KEY_ID }} -k ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ${{ env.workdir_deploy }}
        
    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr 0.0.0.0/0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      if: always()
