name: Docker Image CI

on: workflow_dispatch
    
env:
  workdir: ./app

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Init
      run: go mod init main.go
      working-directory: ${{ env.workdir }}

    - name: Test
      run: go test -coverprofile=coverage.out ./...
      working-directory: ${{ env.workdir }}    

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker Neoway App
      run: docker build . --file Dockerfile --tag rafapmagalhaes/neoway:latest
      working-directory: ${{ env.workdir }}
      
    - name: Push the Docker Neoway App to Registry
      run: docker push rafapmagalhaes/neoway:latest
      working-directory: ${{ env.workdir }}
